export const GET_MOVIES = "GET_MOVIES";
export const STORE_MOVIES = "STORE_MOVIES";

export const GET_MOVIE = "GET_MOVIE";
export const STORE_MOVIE = "STORE_MOVIE";

export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
export const STORE_RECOMMENDATIONS = "STORE_RECOMMENDATIONS";

export const GET_CAST_AND_CREW = "GET_CAST_AND_CREW";
export const STORE_CAST_AND_CREW = "STORE_CAST_AND_CREW";

export const SEARCH_MOVIES = "SEARCH_MOVIES";

export const GET_ACTOR = "GET_ACTOR";
export const STORE_ACTOR = "STORE_ACTOR";

export const GET_MOVIE_CREDITS = "GET_MOVIE_CREDITS";
export const STORE_MOVIE_CREDITS = "STORE_MOVIE_CREDITS";

export const SET_BACKDROP = "SET_BACKDROP";
